"""initial schema from existing models

Revision ID: 9fb76444a01b
Revises:
Create Date: 2026-08-15 13:58:52.901312

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fb76444a01b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "videos",
        sa.Column("video_id", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("upload_date", sa.String(length=32), nullable=True),
        sa.Column("transcript_with_ts", sa.Text(), nullable=True),
        sa.Column("transcript_no_ts", sa.Text(), nullable=True),
        sa.Column("tokens_with_ts", sa.Integer(), nullable=True),
        sa.Column("tokens_no_ts", sa.Integer(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("video_id"),
    )
    op.create_table(
        "summaries_v2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(length=50), nullable=True),
        sa.Column("video_title", sa.String(length=512), nullable=True),
        sa.Column("model_name", sa.String(length=50), nullable=True),
        sa.Column("date_generated", sa.DateTime(), nullable=True),
        sa.Column("concise_summary", sa.Text(), nullable=True),
        sa.Column("key_topics", sa.Text(), nullable=True),
        sa.Column("important_takeaways", sa.Text(), nullable=True),
        sa.Column("comprehensive_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "video_folders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("folder_name", sa.String(length=255), nullable=True),
        sa.Column("original_playlist_id", sa.String(length=255), nullable=True),
        sa.Column("video_id", sa.String(length=50), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.video_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("video_folders")
    op.drop_table("summaries_v2")
    op.drop_table("videos")
    op.drop_table("users")
    op.drop_table("sync_jobs")
    # ### end Alembic commands ###
